# ---------- СТАДИЯ 1: Сборка ----------
FROM golang:1.24.6 AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum и загружаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники проекта
COPY . .

# Собираем бинарник
RUN go build -o server .



# ---------- СТАДИЯ 2: Минимальный образ ----------
FROM debian:bookworm-slim

# Устанавливаем временную зону и утилиты (опционально)
ENV TZ=UTC

# Создаём непривилегированного пользователя
RUN useradd -m appuser

# Создаём директории для приложения
RUN mkdir -p /app/storage/files
RUN chown -R appuser:appuser /app

# Копируем бинарник из стадии сборки
COPY --from=builder /app/server /usr/local/bin/server

# Назначаем рабочую директорию
WORKDIR /app

# Переключаемся на непривилегированного пользователя
USER appuser

# Указываем порт, который слушает Gin
EXPOSE 1244

# Запускаем приложение
ENTRYPOINT ["server"]
